# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://www.{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: true
        # Base the cache on the session cookies. Ignore all other cookies.
        cookies:
            - '/^wordpress_logged_in_/'
            - '/^wordpress_sec_/'
            - 'wordpress_test_cookie'
            - '/^wp-settings-/'
            - '/^wp-postpass/'
            - '/^wp-resetpass-/'
            - 'woocommerce_cart_hash'
            - 'woocommerce_items_in_cart'
            - '/^wp_woocommerce_session_/'
            - 'woocommerce_recently_viewed'
            - '/^store_notice/'

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"
