<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
use Platformsh\ConfigReader\Config;

require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';

$config = new Config();
if ($config->isValidPlatform() && $config->hasRelationship('redis') && extension_loaded('redis')) {
  $credentials = $config->credentials('redis');

   define('WP_REDIS_CLIENT', 'pecl');
   define('WP_REDIS_HOST', $credentials['host']);
   define('WP_REDIS_PORT', $credentials['port']);
}

require_once ABSPATH . 'wp-settings.php';
